# -*- coding: utf-8 -*-
"""Doc Genie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OFwVUo2b8-3swbdwhMEi8Hh8_2Bdg536
"""

!pip install gradio reportlab

import ast
import gradio as gr
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

class DocGenieAnalyzer:

    @staticmethod
    def extract_function_signature(code):

        tree = ast.parse(code)

        for node in ast.walk(tree):

            if isinstance(node, ast.FunctionDef):

                params = []

                for arg in node.args.args:
                    params.append(arg.arg)

                return {
                    "name": node.name,
                    "params": params
                }

def generate_google_docstring(signature):

    params = signature["params"]

    args_text = ""

    for p in params:
        args_text += f"    {p} (Any): Parameter for controlling {p} behavior.\n"

    doc = f"""
Executes {signature["name"]} operation with conditional logic.

Args:
{args_text}

Returns:
    Any: The result of the computation.
"""

    return doc

def generate_numpy_docstring(signature):

    params = signature["params"]

    args_text = ""

    for p in params:
        args_text += f"    {p} : Any\n        Parameter for controlling {p} behavior.\n"

    doc = f"""
\"\"\"
Executes {signature["name"]} operation with conditional logic.

Parameters
----------
{args_text}

Returns
-------
Any
    The result of the computation.
\"\"\"
"""

    return doc

def create_pdf(text):

    file = "docgenie_output.pdf"

    c = canvas.Canvas(file, pagesize=letter)

    c.drawString(100,750,text)

    c.save()

    return file

def create_txt(text):

    file = "docgenie_output.txt"

    with open(file,"w") as f:
        f.write(text)

    return file

def generate_doc(code, style):

    signature = DocGenieAnalyzer.extract_function_signature(code)

    if style == "Google":
        doc = generate_google_docstring(signature)
    else:
        doc = generate_numpy_docstring(signature)

    return doc

def upload_file(file):

    with open(file.name,"r") as f:
        code = f.read()

    return code

with gr.Blocks(theme=gr.themes.Soft()) as app:

    gr.Markdown("# Doc Genie - Python Docstring Generator")

    with gr.Row():

        with gr.Column(scale=3):

            gr.Markdown("### Input Function Code")

            code_input = gr.Textbox(
                lines=12,
                label="Python Function"
            )

            # Upload Files (Python Function க்கு கீழ)
            file_input = gr.File(label="Upload Files")

            file_input.change(
                upload_file,
                inputs=file_input,
                outputs=code_input
            )

            style = gr.Radio(
                ["Google","NumPy"],
                value="Google",
                label="Select Docstring Style"
            )

            generate_btn = gr.Button(
                "Generate Docstring",
                variant="primary"
            )

        with gr.Column(scale=1):

            gr.Markdown("### Export")

            pdf_btn = gr.Button("Download PDF")

            txt_btn = gr.Button("Download TXT")

            pdf_file = gr.File(label="PDF File")

            txt_file = gr.File(label="TXT File")

    gr.Markdown("### Generated Docstring")

    output = gr.Textbox(
        lines=10,
        label="Documentation Output"
    )

    generate_btn.click(generate_doc,[code_input,style],output)

    pdf_btn.click(create_pdf,output,pdf_file)

    txt_btn.click(create_txt,output,txt_file)

app.launch()